### ISSUE TITLE
Listing of all maps

### ISSUE THREAD

**Issue by USGSsakins** [USGS-Astrogeology/PlanetaryGeologicMappers#12]
### User Story
As a web site visitor, I want a single page that provides a sortable/filterable table listing of all of the mapping projects so that I can find maps that meet my research or information needs.

### Definition of done
- [x] Retrieve the list of all mapping projects from the dataset web services as GeoJSON
- [x] A table or other listing of all the mapping projects
- [x] A way to sort the table listing by any of the fields in the table
- [x] A link for each project to get to the specific details for that mapping project
- [x] A way to filter the results in the table based on the values in the table columns

**Comment by AustinSanders** [comment]
#19 When xss is available, we'll need to change the URL from which we're grabbing the JSON.  Should be as simple as changing 1 line.
