### ISSUE TITLE
Mapping Project Details Page

### ISSUE THREAD

**Issue by USGSsakins** [USGS-Astrogeology/PlanetaryGeologicMappers#14]
### User Story
As a web site visitor, I want a page with all of the information about a given mapping project so that I can see what stage the map is in, where it is, who is working on it, and if it is available for download.

### Definition of done
- [x] A web page reading the information for a single mapping project
- [x] An interactive web map showing the border of the project and color coding the project based on the same color coding for the listing of all projects on a planet
- [x] Full details on the project including mapper, progress, download links, dates of milestones

**Comment by AustinSanders** [comment]
#19 Important to remove references to {{id}} when xss endpoint is finished.  At the moment, we're loading from All.json and pulling out the element we want (since there's no filtering).  Once xss is available, we can pull the single element from the web service.

**Comment by AustinSanders** [comment]
Maybe done? The only allowable projection at the moment is 'cylindrical,' so maps not using cylindrical projection appear with incorrect position / size.  Hopefully an easy fix?
