### ISSUE TITLE
Fix issues with current / (Home page)

### ISSUE THREAD

**Issue by USGSsakins** [USGS-Astrogeology/PlanetaryGeologicMappers#36]
The index/home page was migrated as a database entry page instead of it's own template file.  The news items are "static" rather than pulling from the RSS feed.  The current dev site can be viewed at:

http://planetarymapping-dev.wr.usgs.gov/

The production version (in Java) can be viewed at

https://planetarymapping.wr.usgs.gov

The issues that need to be fixed:

- [x] Convert from static page to *.html template
- [x] Change @route for `/` to point at the new template
- [x] Include Javascript to load RSS feed in dynamically as per the example in the current production version
- [x] The bottom left of the main navigation (https://planetarymapping.wr.usgs.gov/Review) points at a missing page.  Use the "menu" template to create this bulleted list for navigation

**Comment by USGSsakins** [comment]
@evindunn-usgs Has this working in the dev Kubernetes server.  Work with him to make sure that when you're changes are incorporated from a Pull Request, that the dev instance is automatically rebuilt.

**Comment by amesamoyers** [comment]
Issue resolved with #37
